# Generated by Django 2.2 on 2019-04-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paczkomat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=128)),
                ('adress', models.CharField(max_length=128)),
                ('post_code', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('dlugosc', models.FloatField(max_length=128)),
                ('szerokosc', models.FloatField(max_length=128)),
                ('dates', models.CharField(max_length=1024)),
            ],
        ),
    ]
